apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: eventix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: eventix/booking-service:latest
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@booking-db:5432/booking-db"
        - name: RABBITMQ_URL
          value: "amqp://eventix:eventix123@rabbitmq:5672/"
        ports:
        - containerPort: 8002
        livenessProbe:
          httpGet:
            path: /
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      initContainers:
      - name: wait-for-db
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h booking-db -p 5432; do echo waiting for database; sleep 2; done;']
      - name: wait-for-rabbitmq
        image: rabbitmq:3.13-management
        command: ['sh', '-c', 'until rabbitmqctl -H rabbitmq status; do echo waiting for rabbitmq; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: eventix
spec:
  selector:
    app: booking-service
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30003
  type: NodePort