name: eventix-api
services:          
  user-db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-db
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres -d user-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  event-db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event-db
    ports:
      - "5433:5432"
    volumes:
      - event-db-data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d event-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  booking-db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking-db
    ports:
      - "5434:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  payment-db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment-db
    ports:
      - "5435:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: eventix
      RABBITMQ_DEFAULT_PASS: eventix123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
    user-db-data:
      driver: local
    event-db-data:
      driver: local
    booking-db-data:
      driver: local
    payment-db-data:
      driver: local
    rabbitmq-data:
      driver: local

networks:
    net:
      driver: bridge